---
sudo: required
dist: xenial

language: php

php:
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  # Download selenium
  - mkdir -p selenium
  - >
    wget -c -O selenium/selenium-server-standalone-3.141.59.jar \
     http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  # Install NPM, Grunt, Bower, Sass
  - sudo apt-get --assume-yes install npm ruby-sass
  - sudo npm install -g bower
  - sudo npm install -g grunt-cli
  # Pull in external code dependencies, build front-end code
  - composer install
  - npm install
  - bower install
  - grunt

before_script:
  # Start selenium
  - >
    /usr/bin/xvfb-run \
     java -jar selenium/selenium-server-standalone-3.141.59.jar > selenium.log &
  # Start container
  - docker-compose up --build -d

script:
  - php vendor/bin/phpcs -n --standard=psr2 cli/ server/ test/ includes/ *.php
  - php vendor/bin/phpunit test/unit/ --coverage-text
  - php vendor/bin/phpunit test/selenium/

after_script:
  - docker-compose down

after_failure:
  - cat selenium.log

cache:
  directories:
  - selenium
...

